class UserInput:
    def __init__(self):
        self.parameters_from_user = [
            {"name": "inputQ",
                "description": "Vykon vymeniku",
                "variable_name": "Q",
                "parse_function": float,
                "unit": "W"},
            {"name": "inputM1",
                "description": "Prutok v trubkovem prostoru",
                "variable_name": "m1",
                "parse_function": float,
                "unit": "kg/s"},
            {"name": "inputM2",
                "description": "Prutok v mezitrubkovem prostoru",
                "variable_name": "m2",
                "parse_function": float,
                "unit": "kg/s"},
            {"name": "inputT11",
                "description": "Teplota na vstupu do trubkoveho prostoru",
                "variable_name": "T11",
                "parse_function": float,
                "unit": "K"},
            {"name": "inputT12",
                "description": "Teplota na vystupu z trubkoveho prostoru",
                "variable_name": "T12",
                "parse_function": float,
                "unit": "K"},
            {"name": "inputT21",
                "description": "Teplota na vstupu do mezitrubkoveho prostoru",
                "variable_name": "T21",
                "parse_function": float,
                "unit": "K"},
            {"name": "inputT22",
                "description": "Teplota na vystupu z mezitrubkoveho prostoru",
                "variable_name": "T22",
                "parse_function": float,
                "unit": "K"},
               
        ]